=== ChaosWang1028/RPC/chaosrpc/chaosrpc-framework/chaosrpc-core/src/main/java/com/chaos/builder/xml/chaos-config.dtd
<?xml version="1.0" encoding="utf-8" ?>
    <!ELEMENT configuration (port?, applicationName?, registry?,
            serializer?, serializeType?, compressType? compressor?,
            loadBalancerType, loadBalancer, idGenerator)>

        <!ELEMENT port ANY>

        <!ELEMENT applicationName ANY>
        <!ATTLIST applicationName

        >
        <!ELEMENT registry EMPTY>
        <!ATTLIST registry
                url CDATA #REQUIRED
                >

        <!ELEMENT serializer EMPTY>
        <!ATTLIST serializer
                class CDATA #REQUIRED
                >
        <!ELEMENT serializeType EMPTY>
        <!ATTLIST serializeType
                type CDATA #REQUIRED
                >

        <!ELEMENT compressor EMPTY>
        <!ATTLIST compressor
                class CDATA #REQUIRED
                >
        <!ELEMENT compressType EMPTY>
        <!ATTLIST compressType
                type CDATA #REQUIRED
                >

        <!ELEMENT loadBalancer EMPTY>
        <!ATTLIST loadBalancer
                class CDATA #REQUIRED
                >
        <!ELEMENT loadBalancerType EMPTY>
        <!ATTLIST loadBalancerType
                type CDATA #REQUIRED
                >

        <!ELEMENT idGenerator EMPTY>
        <!ATTLIST idGenerator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                machineId CDATA #REQUIRED
                >

=== ChaosWang1028/RPC/chaosrpc/chaosrpc-demo/chaosrpc-provider-demo/src/main/resources/chaosrpc.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE configuration SYSTEM "chaos-config.dtd">
<configuration>
    <port>8090</port>
    <applicationName>chaos-rpc-app</applicationName>
    <!-- 二选一 -->
    <compressType type="gzip"/>
    <serializeType type="hessian"/>
<!--    <compressor class="com.chaos.compress.impl.GZIPCompressor" code="1" name="gzip"/>-->
<!--    <serializer class="com.chaos.serialize.impl.HessianSerializer" code="3" name="hessian"/>-->


    <registry url="zookeeper://127.0.0.1:2181"/>
    <loadBalancer class="com.chaos.loadbalance.impl.MinResponseTimeLoadBalancer"/>
    <idGenerator class="com.chaos.IdGenerator" dataCenterId="2" machineId="4"/>
</configuration>
